name: cd

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Build
        run: mvn -q -DskipTests=false package
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kuryenet-jar
          path: target/*.jar
