ALTER TABLE addresses ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE couriers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE couriers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE couriers ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE couriers ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE customers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE customers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE customers_baskets ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE customers_baskets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE customers_baskets ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE customers_baskets ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE providers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE providers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE providers ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE providers ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE roles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE roles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE roles ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE users_roles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE users_roles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE users_roles ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE users_roles ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
