ALTER TABLE addresses ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS version BIGINT;

ALTER TABLE couriers ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE couriers ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE couriers ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);
ALTER TABLE couriers ADD COLUMN IF NOT EXISTS version BIGINT;

ALTER TABLE customers ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS version BIGINT;

ALTER TABLE customers_baskets ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE customers_baskets ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE customers_baskets ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);
ALTER TABLE customers_baskets ADD COLUMN IF NOT EXISTS version BIGINT;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS version BIGINT;

ALTER TABLE providers ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE providers ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE providers ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);
ALTER TABLE providers ADD COLUMN IF NOT EXISTS version BIGINT;

ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS version BIGINT;

ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS version BIGINT;

ALTER TABLE roles ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);
ALTER TABLE roles ADD COLUMN IF NOT EXISTS version BIGINT;

ALTER TABLE users_roles ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users_roles ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE users_roles ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);
ALTER TABLE users_roles ADD COLUMN IF NOT EXISTS version BIGINT;
