logging.level.root=INFO
logging.level.com.gp.KuryeNet=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

management.tracing.sampling.probability=0.5
