logging.level.root=INFO
logging.level.com.gp.KuryeNet=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.orm.jdbc.bind=ERROR

management.tracing.sampling.probability=0.1
